// Generated by scripts/generate-exact-parity-matrices.mjs from the canonical parity matrix.
export const paritySummary = {
  "source": "docs/parity/EXACT_VIDEO_PARITY_MATRIX.json",
  "generatedAt": "2026-08-28T05:54:56.985Z",
  "chapters": [
    {
      "chapter": "CH01",
      "title": "Matriz canónica CH01",
      "features": 41,
      "implemented": 5,
      "partial": 30,
      "blocked": 6,
      "missing": 0,
      "status": "PASS_WITH_NOTES"
    },
    {
      "chapter": "CH02",
      "title": "Matriz canónica CH02",
      "features": 20,
      "implemented": 4,
      "partial": 8,
      "blocked": 8,
      "missing": 0,
      "status": "PASS_WITH_NOTES"
    },
    {
      "chapter": "CH03",
      "title": "Matriz canónica CH03",
      "features": 16,
      "implemented": 3,
      "partial": 5,
      "blocked": 8,
      "missing": 0,
      "status": "PASS_WITH_NOTES"
    },
    {
      "chapter": "CH04",
      "title": "Matriz canónica CH04",
      "features": 17,
      "implemented": 4,
      "partial": 7,
      "blocked": 6,
      "missing": 0,
      "status": "PASS_WITH_NOTES"
    },
    {
      "chapter": "CH05",
      "title": "Matriz canónica CH05",
      "features": 19,
      "implemented": 8,
      "partial": 5,
      "blocked": 6,
      "missing": 0,
      "status": "PASS_WITH_NOTES"
    },
    {
      "chapter": "CH06",
      "title": "Matriz canónica CH06",
      "features": 22,
      "implemented": 10,
      "partial": 3,
      "blocked": 9,
      "missing": 0,
      "status": "PASS_WITH_NOTES"
    },
    {
      "chapter": "CH07",
      "title": "Matriz canónica CH07",
      "features": 18,
      "implemented": 7,
      "partial": 5,
      "blocked": 6,
      "missing": 0,
      "status": "PASS_WITH_NOTES"
    },
    {
      "chapter": "CH08",
      "title": "Matriz canónica CH08",
      "features": 22,
      "implemented": 14,
      "partial": 6,
      "blocked": 2,
      "missing": 0,
      "status": "PASS_WITH_NOTES"
    },
    {
      "chapter": "CH09",
      "title": "Matriz canónica CH09",
      "features": 25,
      "implemented": 13,
      "partial": 8,
      "blocked": 4,
      "missing": 0,
      "status": "PASS_WITH_NOTES"
    },
    {
      "chapter": "CH10",
      "title": "Matriz canónica CH10",
      "features": 10,
      "implemented": 2,
      "partial": 4,
      "blocked": 4,
      "missing": 0,
      "status": "PASS_WITH_NOTES"
    },
    {
      "chapter": "CH11",
      "title": "Matriz canónica CH11",
      "features": 10,
      "implemented": 5,
      "partial": 2,
      "blocked": 3,
      "missing": 0,
      "status": "PASS_WITH_NOTES"
    },
    {
      "chapter": "CH12",
      "title": "Matriz canónica CH12",
      "features": 12,
      "implemented": 5,
      "partial": 5,
      "blocked": 2,
      "missing": 0,
      "status": "PASS_WITH_NOTES"
    },
    {
      "chapter": "CH13",
      "title": "Matriz canónica CH13",
      "features": 18,
      "implemented": 9,
      "partial": 3,
      "blocked": 6,
      "missing": 0,
      "status": "PASS_WITH_NOTES"
    },
    {
      "chapter": "CH14",
      "title": "Matriz canónica CH14",
      "features": 24,
      "implemented": 2,
      "partial": 14,
      "blocked": 8,
      "missing": 0,
      "status": "PASS_WITH_NOTES"
    },
    {
      "chapter": "CH15",
      "title": "Matriz canónica CH15",
      "features": 16,
      "implemented": 3,
      "partial": 8,
      "blocked": 5,
      "missing": 0,
      "status": "PASS_WITH_NOTES"
    },
    {
      "chapter": "CH16",
      "title": "Matriz canónica CH16",
      "features": 9,
      "implemented": 6,
      "partial": 1,
      "blocked": 2,
      "missing": 0,
      "status": "PASS_WITH_NOTES"
    },
    {
      "chapter": "CH17",
      "title": "Matriz canónica CH17",
      "features": 12,
      "implemented": 7,
      "partial": 3,
      "blocked": 2,
      "missing": 0,
      "status": "PASS_WITH_NOTES"
    }
  ],
  "totalRequirements": 311,
  "missing": 0
};
