import type { DoctorAttachment } from '@analiza/contracts';
import type { SearchableOption } from '@/lib/patient-form';

export const doctorSpecialtyOptions = [
  'Alergología e Inmunología Clínica',
  'Alergología e Inmunología Pediátrica',
  'Algología - Medicina del Dolor',
  'Anestesiología',
  'Anestesiología / Medicina Crítica',
  'Audiología Médica',
  'Cardiología',
  'Cardiología Intervencionista - Hemodinamista',
  'Cardiología Pediátrica',
  'Cirugía General',
  'Cirugía Maxilofacial',
  'Cirugía Pediátrica',
  'Cirugía Plástica, Estética y Reconstructiva',
  'Cuidados Intensivos Pediátricos',
  'Cuidados Paliativos',
  'Cuidados Paliativos Pediátricos',
  'Dermatología',
  'Dermatología Pediátrica',
  'Diabetología',
  'Electrofisiología Cardíaca',
  'Endocrinología',
  'Endocrinología Pediátrica',
  'Epidemiología',
  'Gastroenterología',
  'Gastroenterología Pediátrica',
  'Genética',
  'Genética Médica',
  'Geriatría',
  'Ginecología y Obstetricia',
  'Ginecología, Menopausia y Climaterio',
  'Hematología',
  'Hematología Pediátrica',
  'Hematología-Oncología Pediátrica',
  'Hepatología',
  'Infectología',
  'Infectología Pediátrica',
  'Inmunología',
  'Medicina de la Obesidad',
  'Medicina de Urgencias y Emergencias',
  'Medicina de Viajes',
  'Medicina del Adolescente',
  'Medicina Familiar y Comunitaria',
  'Medicina Física y Rehabilitación',
  'Medicina General',
  'Medicina Hiperbárica y Subacuática',
  'Medicina Interna',
  'Medicina Nuclear',
  'Medicina Paliativa',
  'Nefrología',
  'Nefrología Pediátrica',
  'Neonatología',
  'Neumología',
  'Neumología Pediátrica',
  'Neurocirugía',
  'Neurología',
  'Neurología Pediátrica',
  'Nutrición Pediátrica',
  'Nutriología Clínica',
  'Oftalmología',
  'Oncología Clínica',
  'Oncología Médica',
  'Oncología Pediátrica',
  'Oncología Radioterápica',
  'Ortopedia Pediátrica',
  'Ortopedia y Traumatología',
  'Otorrinolaringología',
  'Patología',
  'Pediatría',
  'Psiquiatría',
  'Radiología',
  'Reumatología',
  'Reumatología Pediátrica',
  'Reumatología / Inmunología',
  'Toxicología Clínica',
  'Urgencias Pediátricas',
  'Urología',
  'Técnico(a) en enfermería',
  'Tecnólogo(a) en enfermería',
  'Licenciado(a) en enfermería',
  'Supervisor(a)',
  'Licenciado en Terapia respiratoria',
  'Licenciado en Terapia física',
  'Nutricionista',
  'Psicólogo(a)',
].map((label) => ({ value: label, label })) satisfies SearchableOption[];

type FileMetadataSource = Pick<File, 'name' | 'size' | 'type'>;

/** Metadata only: file bytes belong in a private, RLS-protected storage integration. */
export function toDoctorAttachmentMetadata(
  files: Iterable<FileMetadataSource>,
): DoctorAttachment[] {
  return Array.from(files, (file) => ({
    id: crypto.randomUUID(),
    name: file.name,
    mimeType: file.type || undefined,
    size: file.size,
  }));
}
