// Generated by qa:video-parity:generate. Do not edit manually.
export const videoParitySummary = {
  "generatedAt": "2026-09-02T08:38:16-06:00",
  "sourceSha": null as string | null,
  "functionalFingerprint": "cd8688b74e2004014691eb13b32bff494ddc29bfbe61095ee6f23d349e5e88b0",
  "chapters": 17,
  "total": 210,
  "EXACT": 60,
  "PARTIAL": 102,
  "MISSING": 0,
  "BLOCKED_CLIENT": 1,
  "BLOCKED_INTEGRATION": 3,
  "NOT_TESTABLE": 42,
  "NOT_APPLICABLE": 2
} as const;
