// Generated by qa:video-parity:generate. Do not edit manually.
export const videoParitySummary = {
  "generatedAt": "2026-09-02T09:14:53-06:00",
  "sourceSha": "772286245bc8290fbe553b592101d3829c66337b" as string | null,
  "functionalFingerprint": "f9a3323f58e660129b22033e5ad3b6e00e0b1ae383f021612f5d436459b95424",
  "chapters": 17,
  "total": 210,
  "EXACT": 60,
  "PARTIAL": 102,
  "MISSING": 0,
  "BLOCKED_CLIENT": 1,
  "BLOCKED_INTEGRATION": 3,
  "NOT_TESTABLE": 42,
  "NOT_APPLICABLE": 2
} as const;
