// Generated by qa:video-parity:generate. Do not edit manually.
export const videoParitySummary = {
  generatedAt: '2026-09-03T05:21:17-06:00',
  sourceSha: 'fd81e1f6d426e4cc745b068d1f57944f88cd8520' as string | null,
  functionalFingerprint: '50ce9a927703b31e0a9aa83d8168b0cfaf03d66d3c331e7d13eacd66dcfa6842',
  chapters: 17,
  total: 210,
  EXACT: 52,
  PARTIAL: 85,
  MISSING: 20,
  BLOCKED_CLIENT: 8,
  BLOCKED_INTEGRATION: 3,
  NOT_TESTABLE: 40,
  NOT_APPLICABLE: 2,
} as const;
